name: flake8

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
      run: |
        set -x
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-interaction --no-root
    - name: Run Flake8
      run: poetry run flake8 .
